blank_issues_enabled: false
contact_links:
  - name: FTB Discord
    url: https://ftb.team/discord
    about: "If you don't have an issue and just want to ask a question about the app, this is a great place to go."
