blank_issues_enabled: false
contact_links:
  - name: FTB Discord
    url: https://ftb.team/discord
    about: "If you don't have an issue and just want to ask a question about the app, this is a great place to go."
  - name: FTB Helpdesk
    url: https://feed-the-beast.com/support
    about: "Not sure what you're doing? Just need someone to help you use the app? Try our Helpdesk or our Discord above"
