name: Feature Request
description: Report an issue with the Windows version of the FTB App
labels: ["feature:request"]
body:
  - type: dropdown
    id: os
    validations:
      required: true
    attributes:
      label: What version of the app is the feature intended for?
      multiple: false
      options:
        - All
        - Windows
        - Linux / MacOS
  - type: textarea
    id: request
    attributes:
      label: What is your feature request?
      description: "Please describe in as much detail as possible what your feature request is"
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solve-issue
    attributes:
      label: Does your request solve an issue?
      description: "Is your feature request related to a problem? If so Please describe"
      placeholder: "I'd love it if the app was about to do..."
    validations:
      required: false
  - type: textarea
    id: considered
    attributes:
      label: Describe alternatives you've considered
      description: "If the above isn't viable for us add, what alternatives might you suggest?"
      placeholder: "If that's not possible then maybe we can do it this way..."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the suggestion here
    validations:
      required: false
